server:
  port: 8080

spring:
  application:
    name: blog-service
  
  config:
    import:
      - optional:file:../../.env[.properties]
      - classpath:application-database.yml
      - classpath:application-routes.yml
      - classpath:application-redis.yml
      - classpath:application-weixin.yml
      - classpath:application-storage.yml
      - classpath:application-security.yml
      - classpath:application-mail.yml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
