spring:
  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:1973578950@qq.com}
    password: ${MAIL_PASSWORD:apqficpjjqvtcdca}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
